spring:
  datasource:
    url: jdbc:h2:file:./database/datafile;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    data-password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
logging:
  level:
    org.kingsteff: DEBUG
    root: INFO